<<<<<<< HEAD
# Generated by Django 2.0.2 on 2018-05-16 05:32
=======
# Generated by Django 2.0.2 on 2018-03-28 15:56
>>>>>>> b609d75f2eeb607948a1ca4f768e20c6a4034f73

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='avatars')),
=======
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
>>>>>>> b609d75f2eeb607948a1ca4f768e20c6a4034f73
                ('description', models.CharField(blank=True, max_length=100)),
                ('vk', models.CharField(blank=True, max_length=50)),
                ('telegram', models.CharField(blank=True, max_length=50)),
                ('whatsapp', models.CharField(blank=True, max_length=50)),
                ('viber', models.CharField(blank=True, max_length=50)),
<<<<<<< HEAD
                ('insta', models.CharField(blank=True, max_length=50)),
                ('skype', models.CharField(blank=True, max_length=50)),
=======
>>>>>>> b609d75f2eeb607948a1ca4f768e20c6a4034f73
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
