# Generated by Django 2.0.2 on 2018-05-08 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0002_auto_20180508_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='skype',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
