# Generated by Django 2.0.2 on 2018-05-08 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0003_profile_skype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='avatar_image/blank.jpg', upload_to='avatar_image'),
        ),
    ]
